name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o atcs-windows-amd64.exe .

      - name: Build for Windows (arm64)
        run: |
          GOOS=windows GOARCH=arm64 go build -o atcs-windows-arm64.exe .

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o atcs-linux-amd64 .

      - name: Build for Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o atcs-linux-arm64 .

      - name: Build for macOS (amd64)
        run: |
          GOOS=darwin GOARCH=amd64 go build -o atcs-darwin-amd64 .

      - name: Build for macOS (arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o atcs-darwin-arm64 .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            atcs-windows-amd64.exe
            atcs-windows-arm64.exe
            atcs-linux-amd64
            atcs-linux-arm64
            atcs-darwin-amd64
            atcs-darwin-arm64

